name: 'Fancy name of the action'
description: 'Short description'
author: 'name I want to become famous with'
inputs:
  github-token:
    description: 'token'
    required: true
  github-lalala:
    description: 'lalala'
    required: true
runs:
  using: 'node12' # необходимая версия ноды – важно
  main: 'dist/index.js'
branding: # как будет выглядеть иконка экшена в маркетплейсе
  icon: 'terminal'
  color: 'blue'

